### ISSUE TITLE
NettClientRouter decoder: readerIndex(96) + length(1) exceeds writerIndex(96)

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#211]
Version:  0.1+922 (I think I installed it in April/May ... may _not_ be accurate, sorry, submitted on behalf of Johnny)

The situation is this: I’m using StreamView, I sent 25 messages (different stream ids), each around 20Mb, there is no error during send. During reading, the following exception is thrown (see below). The trigger of this problem seems like the number of messages, I.e. I don’t get this problem when I’m sending only 10 messages (this problem actually did not initially happen for 25 messages, but for 75 messages, it just started happening for 25 messages recently).

```
[2016-08-10 11:20:10,978] ERROR Exception during channel handling. (org.corfudb.runtime.clients.NettyClientRouter)
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(96) + length(1) exceeds writerIndex(96): SlicedAbstractByteBuf(ridx: 96, widx: 96, cap: 96/96, unwrapped: UnpooledUnsafeDirectByteBuf(ridx: 100, widx: 100, cap: 65536))
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:418)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32)
at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:283)
at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(96) + length(1) exceeds writerIndex(96): SlicedAbstractByteBuf(ridx: 96, widx: 96, cap: 96/96, unwrapped: UnpooledUnsafeDirectByteBuf(ridx: 100, widx: 100, cap: 65536))
at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1178)
at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:587)
at org.corfudb.protocols.wireprotocol.LogUnitReadResponseMsg.fromBuffer(LogUnitReadResponseMsg.java:150)
at org.corfudb.protocols.wireprotocol.CorfuMsg.deserialize(CorfuMsg.java:166)
at org.corfudb.protocols.wireprotocol.NettyCorfuMessageDecoder.decode(NettyCorfuMessageDecoder.java:20)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
... 7 more
```

**Comment by slfritchie** [comment]
Update: I've managed to provoke the same exception while using the `master` branch at commit 2e68756c1107be308e8ddca89212629b07d4abc0, both server-side and client-side code.

Also worthwhile noting that when the above error happens on the client-side, the server side also registers an error on the console.  It isn't clear to me which error happens first.

    14:43:02.679 ERROR [event-0] o.c.p.w.NettyCorfuMessageEncoder - Error during serialization!
     io.netty.util.IllegalReferenceCountException: refCnt: 0
            at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1189)

**Comment by slfritchie** [comment]
November review: attempt to test with the setup below hit #304 instead.

    for i in `seq 1 100`; do /bin/echo -n $i "" ; cat /tmp/20-mbyte-input-file | ./bin/corfu_stream -i s$i -c localhost:8000 write; done

**Comment by Maithem** [comment]
Can you trying your test with this patch https://github.com/CorfuDB/CorfuDB/pull/317
I think its fixed now

**Comment by slfritchie** [comment]
I haven't seen for quite a while the error reported by this ticket, "NettClientRouter decoder: readerIndex(96) + length(1) exceeds writerIndex(96)".  I just tried again using #317 and still don't see it.  I'll close now, and I'll keep an eye out if it happens again.
